[package]
name = "bevy_smooth_pixel_camera"
version = "0.1.0"
edition = "2021"
authors = ["Doonv"]
description = "Smooth pixel-perfect camera for Bevy"
documentation = "http://docs.rs/bevy_rapier2d"
repository = "https://github.com/dimforge/bevy_rapier"
exclude = ["assets/"]
keywords = ["game", "gamedev", "graphics", "bevy", "pixel", "pixel-perfect"]
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.3"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
